# Generated by Django 3.2 on 2023-11-13 03:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('difficulty', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(choices=[('CS', 'Coming Soon'), ('AV', 'Available'), ('OG', 'On Going'), ('FI', 'Finished')], default='CS', max_length=2)),
                ('image_url', models.ImageField(null=True, upload_to='cms-xpert/course/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('occupation', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('linkedinUrl', models.CharField(blank=True, max_length=128, null=True)),
                ('profileImageUrl', models.ImageField(null=True, upload_to='cms-xpert/teacher_profile/')),
                ('companyImageUrl', models.ImageField(null=True, upload_to='cms-xpert/teacher_profile_comapny/')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='course.course')),
                ('course_overview', models.TextField()),
                ('reason', models.TextField()),
                ('result', models.TextField()),
                ('certificate_image_url', models.ImageField(null=True, upload_to='cms-xpert/course_detail/')),
                ('skill', models.TextField()),
            ],
            options={
                'verbose_name': 'Course Detail',
                'verbose_name_plural': 'Course Details',
                'db_table': 'course_detail',
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50, null=True)),
                ('desciption', models.TextField()),
                ('image_url', models.ImageField(null=True, upload_to='cms-xpert/testimony/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Testimony',
                'verbose_name_plural': 'Testimonies',
                'db_table': 'testimony',
            },
        ),
        migrations.CreateModel(
            name='CourseStudyMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('image_url', models.ImageField(null=True, upload_to='cms-xpert/course_study/')),
                ('course', models.ManyToManyField(to='course.Course')),
            ],
            options={
                'verbose_name': 'Course Study Method',
                'verbose_name_plural': 'Course Study Methods',
                'db_table': 'course_study_method',
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starting_week', models.IntegerField()),
                ('ending_week', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Course Schedule',
                'verbose_name_plural': 'Course Schedules',
                'db_table': 'course_schedule',
            },
        ),
        migrations.CreateModel(
            name='CoursePrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('discount_percentage', models.IntegerField()),
                ('type', models.CharField(choices=[('BL', 'Belajar'), ('SR', 'Sertifikasi')], default='BL', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Course Price',
                'verbose_name_plural': 'Course Prices',
                'db_table': 'course_price',
            },
        ),
        migrations.CreateModel(
            name='CourseFaq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=128)),
                ('answer', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Course Faq',
                'verbose_name_plural': 'Course Faqs',
                'db_table': 'course_faq',
            },
        ),
        migrations.CreateModel(
            name='CourseCurriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('file', models.FileField(null=True, upload_to='cms-xpert/course_curriculum/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Course Curriculum',
                'verbose_name_plural': 'Course Curriculums',
                'db_table': 'course_curriculum',
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('Text', 'Text'), ('Video', 'Video')], default='Text', max_length=10)),
                ('description', models.TextField()),
                ('ordering', models.IntegerField()),
                ('youtube_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='CourseBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('AV', 'Available'), ('SO', 'Sold Out')], default='AV', max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Course Batch',
                'verbose_name_plural': 'Course Batches',
                'db_table': 'course_batch',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.program'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='course.Teacher'),
        ),
    ]
