# Generated by Django 3.2 on 2023-11-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='coursecurriculum',
            name='file',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='certificate_image_url',
        ),
        migrations.AddField(
            model_name='course',
            name='certified_participant_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='participant_amount',
            field=models.IntegerField(default=0),
        ),
    ]
