# Generated by Django 3.2 on 2023-11-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalaccount',
            name='occupancy_info',
        ),
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
